### ISSUE TITLE
Kunena Latest - Bad value follow for attribute rel on element a:

### ISSUE THREAD

**Issue by csbalazs** [Kunena/Kunena-Addons#153] opened 2013-07-06 21:55 UTC
If u chose Show categories in Category Filter in Basic Options, the Markup Validation Service said: Bad value follow for attribute rel on element a: The string follow is not a registered keyword or absolute URL.

**Comment by schmatzler** [comment] 2015-04-17 16:34
rel=follow is defined in lib/kunena.link.class.php and various files of the blue_eagle template.

The problem is that rel=follow never existed. If we want to specify that a link has to be followed, we just omit rel=nofollow and do nothing at all.

Imho the correct solution would be to remove all references to rel=follow.

**Comment by severdia** [comment] 2016-04-25 00:20
There is no such thing as `rel="follow"` because that's the default. There is only `rel="nofollow"`. Please remove the `rel="follow"` attributes from the Kunena Latest Module.

**Comment by 810** [comment] 2016-08-10 20:24
fixed on K5.0.1

**Closed by 810** 2016-08-10 20:24 UTC
