### ISSUE TITLE
The text / html-code of Rules or Help Pages is not saved if the number of characters exceeds the ~ 15,000

### ISSUE THREAD

**Issue by inscriptios** [Kunena/Kunena-Addons#190] opened 2016-02-23 14:32 UTC
When you create a page with the rules as described here: www.kunena.org/docs/en/faq/rules-or-help-pages using the text / html-code is not saved if the number of characters exceeds the ~ 15,000,

**Comment by 810** [comment] 2016-02-23 15:29
try to use admin tools. then change collation -> UTF-8 Multibyte

**Comment by inscriptios** [comment] 2016-02-24 18:32
But there is no such option there: ![default](https://cloud.githubusercontent.com/assets/5901987/13296284/ff746f26-db3d-11e5-9682-2c1930a5c135.png)

**Comment by 810** [comment] 2016-02-24 18:41
you need to use the admin tools component, Also joomla is working on the migration on j3.5

But maybe you hoster doesn't support that, ask your hoster to update their software

**Comment by rich20** [comment] 2016-02-24 18:53
Github should not be used for support questions. That's not a bug with Kunena Addons.

**Comment by inscriptios** [comment] 2016-02-24 18:58
If you sure that's not bug then let's close this issue.

**Comment by 810** [comment] 2016-02-24 19:46
see forum, for fix. closing this issue

**Closed by 810** 2016-02-24 19:46 UTC
